load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "number",
    hdrs = ["number.h"],
    srcs = ["number.cpp"],
    deps = [
    ]
)

cc_library(
    name = "result",
    hdrs = ["result.h"],
    deps = []
)
cc_library(
    name = "regex_helpers",
    hdrs = ["regex_helpers.h"],
    deps = [":result",]
)

cc_library(
    name = "grammar",
    hdrs = ["grammar.h"],
    deps = [":result",":regex_helpers"]
)

cc_library(
    name = "grammar_new",
    hdrs = ["grammar_new.h"],
    deps = [":result",":regex_helpers","@boost.variant"]
)



cc_binary(
    name = "test_recursive_wrapper",
    srcs = ["test_recursive_wrapper.cpp"],
    deps = ["@boost.variant"]
)
